//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace creatMovie.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Favorite_Actor
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public int actor_id { get; set; }
    
        public virtual Actor Actor { get; set; }
        public virtual User User { get; set; }
    }
}
