//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace creatMovie.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IMDbEntities2 : DbContext
    {
        public IMDbEntities2()
            : base("name=IMDbEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Actor> Actors { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<Director> Directors { get; set; }
        public virtual DbSet<Favorite_Actor> Favorite_Actor { get; set; }
        public virtual DbSet<Favorite_Director> Favorite_Director { get; set; }
        public virtual DbSet<Favorite_Movie> Favorite_Movie { get; set; }
        public virtual DbSet<like> likes { get; set; }
        public virtual DbSet<Movy> Movies { get; set; }
        public virtual DbSet<Staff> Staffs { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
